### ISSUE TITLE
dnscontrol updating registrar nameservers every push

### ISSUE THREAD

**Issue by silverl** [StackExchange/dnscontrol#473]
I'm using R53 and Google Cloud DNS together, as a dual-hosted DNS. The registrar for the domain is R53.

I'm trying to prune down the list of nameservers to 2 from Route53 and 2 from Google Cloud DNS for a total of 4 nameservers. I see this is how stackoverflow has done it as well.

In my `dnsconfig.js` I've tried specifying the argument to DnsProvider to limit it to 2 nameservers, like: 

```
DnsProvider(ROUTE53,2),
DnsProvider(GCLOUD,2),
```

Each time I do a push, dnscontrol is attempting to update/set the same nameservers for the Route53 registrar. dnscontrol reports this is successful. I get emails every time from AWS indicating `Domain details update for example.com succeeded`

I've also tried explicitly setting nameservers with `NAMESERVER()`. Same result.

I understand that Route 53 assigns a delegation set of 4 AWS name servers upon domain creation. In the Route 53 web UI, I can change the name servers for the registered domain so I have 2 AWS and 2 Google nameservers. This doesn't seem to matter to dnscontrol. I've also read that you cannot modify the delegation set in the Web UI, you must use the CLI.

Querying the hosted zone with `aws route53 get-hosted-zone` still returns the original delegation set of 4 AWS namservers. Leaves me wondering what I'm actually changing in the Web UI.

It seems to me that dnscontrol reads the nameserver list from the assigned DelegationSet, seeing that that list of 4 AWS nameservers differs from the 4 I'm attempting to set, and always thinks an update is required.

I understand the delegation set is immutable, and perhaps I would need to tear down the zone and recreate it using a custom delegation set. That is risky and hard. So I'm wondering if I'm just doing it wrong.

I'm also puzzled as to why dnscontrol keeps telling me it's updated the registrar, yet keeps updating it every push.

**Comment by captncraig** [comment]
I haven't used r53 as a registrar myself, so I am not clear what they are doing. 

It almost sounds like they are trying to be clever and help you out. Possibly by not actually accepting a mixed set of nameservers. But a few thoughts I have that may help debugging:

1. I expect `aws route53 get-hosted-zone` will always have the same 4 aws name servers. That is the endpoint that reports which aws nameservers will physically respond to queries for the zone, not necessarily which are registered upstream.

2. dnscontrol should be creating `NS` records for all of the *registered* nameservers you requested. That is 2 from r53 and 2 from google cloud. Is that getting set properly?

3. If you query the NS records from the upstream registry, what is returned? ie what happens if you query NS from the .com nameservers for your domain? That is what r53 is actually registering upstream.

**Comment by silverl** [comment]
Hi, cap,

1. I agree on point 1.
2. The 4 NS records I want are getting created successfully in the zone. The domain is `trackabout.com`:

```
$ dig @ns-1195.awsdns-21.org trackabout.com NS

; <<>> DiG 9.14.0 <<>> @ns-1195.awsdns-21.org trackabout.com NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9163
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;trackabout.com.                        IN      NS

;; ANSWER SECTION:
trackabout.com.         86400   IN      NS      ns-1195.awsdns-21.org.
trackabout.com.         86400   IN      NS      ns-17.awsdns-02.com.
trackabout.com.         86400   IN      NS      ns-cloud-d1.googledomains.com.
trackabout.com.         86400   IN      NS      ns-cloud-d2.googledomains.com.

;; Query time: 16 msec
;; SERVER: 205.251.196.171#53(205.251.196.171)
;; WHEN: Wed May 15 11:15:25 Central Daylight Time 2019
;; MSG SIZE  rcvd: 174

$ dig @ns-cloud-d1.googledomains.com trackabout.com NS

; <<>> DiG 9.14.0 <<>> @ns-cloud-d1.googledomains.com trackabout.com NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55176
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;trackabout.com.                        IN      NS

;; ANSWER SECTION:
trackabout.com.         86400   IN      NS      ns-17.awsdns-02.com.
trackabout.com.         86400   IN      NS      ns-1195.awsdns-21.org.
trackabout.com.         86400   IN      NS      ns-cloud-d1.googledomains.com.
trackabout.com.         86400   IN      NS      ns-cloud-d2.googledomains.com.
```

3. See 2.

When I run dnscontrol preview after having done a success push, I get this puzzling output:

```
PS C:\Code\dns\dnscontrol> dnscontrol preview
******************** Domain: trackabout.com
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...0 corrections
----- DNS Provider: r53...0 corrections
----- Registrar: r53...1 correction
#1: Update nameservers ns-1195.awsdns-21.org,ns-17.awsdns-02.com,ns-cloud-d1.googledomains.com,ns-cloud-d2.googledomains.com -> ns-1195.awsdns-21.org,ns-17.awsdns-02.com,ns-cloud-d1.googledomains.com.,ns-cloud-d2.googledomains.com.
```

It wants to rewrite the registrar, setting the exact values that it recognizes are already correct.

**Comment by captncraig** [comment]
Oh, I wonder if it just needs to sort both sides consistently. That is my guess. Let me make a quick update.

**Comment by captncraig** [comment]
Oh, nope. There are dots after the gcloud nameservers in your output.  That's also a bug that I need to track down.

**Comment by captncraig** [comment]
I just pushed 6d6f685f70844e1093509578ff1196b3df6425fb which I believe will fix your issue and make things more consistent in the future. Can you test from master?

**Comment by silverl** [comment]
Not a go expert here. How would I update an existing go package?

**Comment by silverl** [comment]
figured it out. Seems fixed! Looks good to me!

**Comment by silverl** [comment]
thank you thank you thank you

**Comment by jbfriedrich** [comment]
I think I have the same issue with the INWX provider: 

```
$ dnscontrol preview
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "lockfile.org"
******************** Domain: lockfile.org
1 correction (inwx)
#1: Update nameservers ns.inwx.de,ns2.inwx.de,ns3.inwx.eu -> ns.inwx.de,ns.inwx.de,ns2.inwx.de,ns2.inwx.de,ns3.inwx.eu,ns3.inwx.eu
Done. 1 corrections.
```

It does it with every domain I have, even though there are no changes at all. All three NS are already set. I thought it was a configuration problem on my end, but it still happens with the simplified version:

```
// Registrat and DNS configuration

var REG_NONE = NewRegistrar("none");
var DNS_BIND = NewDnsProvider("bind");

var REG_INWX = NewRegistrar("inwx");
var DNS_INWX = NewDnsProvider("inwx");

// Default configuration for INWX and Hetzner 
// TODO: Cloudflare, DigitalOcean

var HETZNER_SERVER = [
    A("@", "162.55.103.197"),
    AAAA("@", "2a01:4f8:271:5a15::2"),
    CAA("@", "issue", "letsencrypt.org"),
]

var INWX_NS = [
    NAMESERVER("ns.inwx.de."),
    NAMESERVER("ns2.inwx.de."),
    NAMESERVER("ns3.inwx.eu."),
    //SOA("@", "ns.inwx.de.", "hostmaster.inwx.de", 10800, 3600, 604800, 900),
]

// MX configuration for INWX

var INWX_MX = [
    MX("@", 10, "smtp-in0.prod0.webspace.bz."),
    MX("@", 20, "smtp-in1.prod0.webspace.bz."),
    TXT("prod0.webspacebz._domainkey", "v=DKIM1;k=rsa;p=SHORTENEDFORREADABILITY"),
    TXT("@", "v=spf1 a mx include:_spf.webspace.bz -all"),
    TXT("_dmarc", "v=DMARC1; p=reject;")
]

D("lockfile.org", REG_INWX, DnsProvider(DNS_INWX),
    DefaultTTL("900"),
    NAMESERVER_TTL("900"),
    INWX_NS,
    INWX_MX,
    HETZNER_SERVER
);
```

**Comment by tlimoncelli** [comment]
Note to self:

if you see every nameserver twice:

> #1: Update nameservers [ns.inwx.de](http://ns.inwx.de/),[ns2.inwx.de](http://ns2.inwx.de/),[ns3.inwx.eu](http://ns3.inwx.eu/) -> [ns.inwx.de](http://ns.inwx.de/),[ns.inwx.de](http://ns.inwx.de/),[ns2.inwx.de](http://ns2.inwx.de/),[ns2.inwx.de](http://ns2.inwx.de/),[ns3.inwx.eu](http://ns3.inwx.eu/),[ns3.inwx.eu](http://ns3.inwx.eu/)

There's a good chance you're getting a complete set from the parent DNS service (the registrar) AND you've included `NAMESERVER()` statements.  Remove the `NAMESERVER()` statements and you'll be fine.

**Comment by jbfriedrich** [comment]
Thank you! Ah, I did not realize it works that way. But it makes perfect sense now. Thank you for the quick reply. I already deleted the comment when I realized it is not related and wanted to file a separate issue for it. But this is now not necessary anymore ☺️.
